language: node_js
node_js:
  - 'lts/*'

matrix:
  include:
    - name: 'Build and Test'
      script:
        - npm run build -s
        - npm test

    - name: 'Coverage'
      script:
        - jest --coverage --coverageReporters=text-lcov | coveralls

    - name: 'Lint'
      script:
        - npm run lint -s

branches:
  only:
    - master
    # Tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
